### ISSUE TITLE
Investigate creating Ares replacement

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/addons#8]
Ares appears to be, or close to being, abandonware. A number of features from Ares are very useful and other ares are lacking. We wish to investigate the possibilities of creating our own system, containing some of the features we find useful as well as new ideas of our own.

**Comment by Fourjays** [comment]
One idea that many Zeuses would find useful is the ability to directly control which units are located on the headless clients.

**Comment by adios113** [comment]
This is the exact reason i started working on my addon "Crow".
It's aim is to expand Zeus features with our own ideas, improvements much needed by our Mission Makers. I stopped developing the addon itself for a while, since my hands were required elsewhere and there was no enough interest in it, yet. 

I would love to continue working on it, since I think that mod making is my strongest area of expertise.

**Currently working features of "Crow" in the latest build from January:**
https://github.com/blackwatchint/Old_BWINT_Addons/tree/master/BWINT_Crow

- Our very own Main Menu intro, containing a video with our logo in a loop with custom Main menu music. Created on Virtual Reality Map, to decrease loading time as well.

- Armory is now part of the Addon instead of the map. You can place Armory trough the editor and even trough Zeus on any object. (Porting new BWI addons we are currenly using is not a problem either). Main goal is to decrease the template's size and improve the loading time slightly, as well as increase a performance just a little.

- Weather Custom Modules, such as: Desert Storm, Blizzard, Dynamic Fog Changer (Current Fog Changer in Zeus is not utilising the newest setFog array and has JIP issues)

- Custom 3D Enviromental Sound to place by Zeus with Firefights, Combat Ambience

**Additinal modules were planned as well, such as:**

- Additional Fire Support capabilities for Zeus (ex. Nuke with selectable killing range; explosion strenght, support of modded helicopters, aircrafts to do gun runs, rocket strikes; Napalms and such)

- New factions to fight with/as, utilising simple uniform retextures - Vietcong was planned with planned ALiVE compatibility

- Additional ACE support for Zeus

- and more features, I do not recall at the moment.

**Comment by Fourjays** [comment]
Completed as part of modpack reset development.
